import numpy as np
import torch
from NeuNAC_Watermark import NeuNAC
import torch.nn as nn

class TinyDNN(nn.Module):
    def __init__(self):
        super(TinyDNN, self).__init__()
        self.fc1 = nn.Linear(64, 32)
        self.fc2 = nn.Linear(32, 16)
        self.fc3 = nn.Linear(16, 20)

    def forward(self, x):
        x = torch.relu(self.fc1(x))
        x = torch.relu(self.fc2(x))
        return self.fc3(x)

def main():
    # --- EMBEDDING SECTION BEGINS --- #
    # Model is trained, ready to use. For now, we use dummy.
    model = TinyDNN()

    # User has to create this by themselves as a key.
    klt_matrix_key = np.random.randn(32, 32)
    klt_matrix_key, _, _ = np.linalg.svd(klt_matrix_key)  # Make it KLT basis. U @ U.T = I

    wn = NeuNAC(klt_basis=klt_matrix_key, precision=2)  # 2 keys generated by the user are given
    model, klt_mean = wn.embed_watermark(
        model)  # We already have 2 keys, embedding procedure gives + 1 key as klt_mean.

    np.save("new_klt_basis.npy", klt_matrix_key)  # The key produced by the user is saved.
    np.save("new_klt_mean.npy", klt_mean)  # The key produced by the model is saved.

    torch.save(model.state_dict(), "new_watermarked_model.pth")  # The embedded model is saved.
    print("Model saved with embedded watermark: new_watermarked_model.pth")
    # --- EMBEDDING SECTION ENDS --- #

    # --- TEST SECTION BEGINGS --- #

    loaded_model = TinyDNN()
    loaded_model.load_state_dict(torch.load("new_watermarked_model.pth", map_location="cpu"))
    # loaded_model.eval()

    klt_matrix_key = np.load("new_klt_basis.npy")
    klt_mean = np.load("new_klt_mean.npy")

    wn = NeuNAC(klt_basis=klt_matrix_key, precision=2)  # Don't forget, precision value is also a key.
    pus, extracted_bits = wn.extract_watermark(loaded_model, klt_matrix_key, klt_mean)
    verified = wn.verify_watermark(pus, extracted_bits)
    print('Verified:', verified)

    # --- TEST SECTION ENDS --- #


if __name__ == "__main__":
    main()